enable_default_scoreboard: true
default_scoreboard: "default"

enable_restricted_scoreboards: false
restricted_scoreboards:
 scoreboard2: "permission.for.scoreboard2"

enable_perworld_scoreboards: false
world_scoreboards: 
 scoreboardworld: "world"
 scoreboardend: "world_the_end"

allow_placeholders_in_title: false

scoreboard_update_rate: 1

save_scoreboard_preferences: false

mysql: false
host: "127.0.0.1"
port: 3306
username: "root"
password: "pass"
database: "harmonyboard"


